---
lighthouse_version: "4.5.0"
lighthouse_port: 8080
clickhouse_host: "localhost"
clickhouse_port: 8123
clickhouse_user: "default"
clickhouse_password: ""
clickhouse_database: "default"
nginx_server_name: "localhost"---
# defaults file for ansible-role-lighthouse
