---
- name: Установка Vector
  ansible.builtin.apt:
    name: vector
    state: present
  tags: vector

- name: Создание директории для конфигураций Vector
  ansible.builtin.file:
    path: /etc/vector
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags: vector

- name: Настройка Vector для сбора логов Lighthouse
  ansible.builtin.template:
    src: lighthouse-vector.conf.j2
    dest: /etc/vector/lighthouse.conf
    owner: root
    group: root
    mode: '0644'
  tags: vector
  notify: restart vector

- name: Включение и запуск Vector
  ansible.builtin.systemd:
    name: vector
    state: started
    enabled: yes
    daemon_reload: yes
  tags: vector

- name: Проверка установки Vector
  ansible.builtin.command: vector --version
  register: vector_version
  changed_when: false
  tags: vector
